### ISSUE TITLE
Universal EFT modal 

### ISSUE THREAD

**Issue by KirstenBoWinkle** [daxko/design#19]
A way for us the display EFT forms throughout the system

![eft form final](https://cloud.githubusercontent.com/assets/10051072/8014570/8e7969f0-0b97-11e5-98d1-ff4cb97f25b1.png)

**Comment by kbowman17** [comment]
Also need to talk about if we are going to have it show up in all other places where EFT forms are

**Comment by scurker** [comment]
I'm not sure we really want people to replicate this form. I agree there needs to be a standard for it, but I'm not sure this is the right place for it.

**Comment by scurker** [comment]
Issue cleanup
