### ISSUE TITLE
Discuss breadcrumbs and page titles

### ISSUE THREAD

**Issue by KirstenBoWinkle** [daxko/design#21]
There are rarely any page titles in Ops. Uses breadcrumbs for "title". We need to add titles (make title requirement in style guide) and also decide the type of breadcrumbs we want to use. Engage breadcrumbs are separated from the main nav bar, and is attached the main nav bar in Ops.

**Comment by scurker** [comment]
Adding screenshots for reference.

**Operations**
![screen shot 2015-06-05 at 3 46 07 pm](https://cloud.githubusercontent.com/assets/1062039/8014941/7260ef74-0b9a-11e5-927c-04d0b85b2053.png)

**Accounting**
![screen shot 2015-06-05 at 3 47 53 pm](https://cloud.githubusercontent.com/assets/1062039/8014938/6f18c440-0b9a-11e5-8fdb-715334f46184.png)

**Engage**
![screen shot 2015-06-05 at 3 48 29 pm](https://cloud.githubusercontent.com/assets/1062039/8014939/708a85e8-0b9a-11e5-9a19-e54f669d3a90.png)
