### ISSUE TITLE
Need basic form css

### ISSUE THREAD

**Issue by scurker** [daxko/design#23]
There's some default input styles right now, but they're not documented and we need to determine a clean way to layout forms for desktop and mobile devices.

**Comment by scurker** [comment]
Right now, we can do very basic form (horizontal) styling including inputs, radios, checkboxes, and textareas. We will need to consider how to approach input widths.

![screen shot 2015-06-09 at 12 06 57 pm](https://cloud.githubusercontent.com/assets/1062039/8064412/16d498fa-0ea0-11e5-88f0-ab57c95cafd8.png)

**Comment by jshores** [comment]
Here's just a few examples that we can talk through should top aligned form labels be an option. 

For this one we would need to figure out what needed to be grouped on a single line and what needs to have it's own line. For example, gender and date birth could be on a single line.

![top aligned_1](https://cloud.githubusercontent.com/assets/1881394/8130639/cb80f77c-10d9-11e5-8f8d-758b0c9c04d4.png)

Second, I still have name grouped, but not address. Why you ask..just to give some more visual as to the things we will need to decide.

![top aligned_2](https://cloud.githubusercontent.com/assets/1881394/8130649/e38f0e6c-10d9-11e5-83f6-2e480e8e0c4f.png)

Third, all fields have their own line. Now we start seeing the amount of space that these forms can fill.

![top aligned_3](https://cloud.githubusercontent.com/assets/1881394/8130652/e91578d0-10d9-11e5-80d0-57dfc522166f.png)

Fourth, I removed the idea of field length affordance and made all fields the same length. 

![top aligned_4](https://cloud.githubusercontent.com/assets/1881394/8130656/ef14b12e-10d9-11e5-952c-c938137d4cc4.png)

Hopefully these will help continue discussion on forms from this week's team meeting.

**Comment by scurker** [comment]
From a visual expectation, the first would be the most consistent with how people may visualize information. With the last one, I don't think fields should generally be the same length within a certain rule. [This article](http://baymard.com/blog/form-field-usability-matching-user-expectations) provides some good reasoning on what users typically expect.

For example, if you have an address 1 field that can contain up to 50 characters, and an address 2 field that can contain up to 40 characters, you should not see this:

![screen shot 2015-06-12 at 8 24 34 am](https://cloud.githubusercontent.com/assets/1062039/8130987/d1a98300-10dc-11e5-9e48-b1ebfecc5873.png)

At the same time, something like this should be acceptable:

![screen shot 2015-06-12 at 8 29 06 am](https://cloud.githubusercontent.com/assets/1062039/8131036/1ab6a91a-10dd-11e5-8457-8feeedbceed9.png)

At some point I need to put into the style a way to cleanly size inputs, but right now there's nothing specifying input width.

**Comment by scurker** [comment]
Also added custom styling for selects to better match the rest of our inputs.

**Chrome**
![select-chrome](https://cloud.githubusercontent.com/assets/1062039/8211000/5439b9f6-14da-11e5-9e88-9d90e1d554a7.png)

**Firefox**
![select-firefox](https://cloud.githubusercontent.com/assets/1062039/8211015/6b042bb2-14da-11e5-98e1-7967fe52b8fc.png)

**IE10+**
![select-ie10](https://cloud.githubusercontent.com/assets/1062039/8211023/73a2a14a-14da-11e5-87b8-cd6663427fa1.png)

**IE9**
IE9 doesn't allow you to remove the native select dropdown indicator, so we hide our custom one and display the native one.
![select-ie9](https://cloud.githubusercontent.com/assets/1062039/8211038/862da238-14da-11e5-85bc-879206e95b46.png)

**Comment by scurker** [comment]
We can now support both variations of the layout above, so closing this.
