### ISSUE TITLE
Marking required vs optional fields on forms and layout

### ISSUE THREAD

**Issue by jshores** [daxko/design#29]
Indication of required fields is most useful when
• There are lots of fields
• But very few are required
• Enables users to scan form to see what needs to be filled in

Indication of optional fields is most useful when
• Very few fields are optional

A few best practices by Luke W
• Try to avoid optional fields
• If most fields are required: indicate optional fields
• If most fields are optional: indicate required fields
• Text is best, but \* often works for required fields
• Associate indicators with labels

Here are a few examples to start a discussion. This should be a quick one to decide.

![required vs optional](https://cloud.githubusercontent.com/assets/1881394/8131546/8f6ae0c0-10e0-11e5-9f1f-49166ff1c33b.png)

**Comment by scurker** [comment]
I'm against using * for required fields. It seems [research shows](http://preibusch.de/publications/Preibusch-Krol-Beresford__voluntary_over-disclosure.pdf) that optional is better than having required and users tend to fill out more fields with when they're not directed to.

Also, I have a feeling with a sass based product our users are going to tend to fill out all the information they have available so noting something as optional or required doesn't really give us or our users a lot of benefit.
