### ISSUE TITLE
Add support to toggle content across viewport breakpoints

### ISSUE THREAD

**Issue by wshirey** [daxko/design#67]
For example, .col-*sm|md|lg*-0 would be defined as

```sass
@media (max-width: $grid-sm-width) {
  .grid .col-sm-0 {
    display: none !important;
  }
}

@media (max-width: $grid-md-width) {
  .grid .col-md-0 {
    display: none !important;
  }
}

@media (max-width: $grid-lg-width) {
  .grid .col-lg-0 {
    display: none !important;
  }
}
```

**Comment by scurker** [comment]
This seems like something we could do. What are some examples of places we would want to hide content like this?

**Comment by wshirey** [comment]
Good example would be hiding side nav content when on mobile.

**Comment by scurker** [comment]
@wshirey I'm starting to think about this. It might be better to have display utility classes, so it's not specific to the grid. Maybe something like `.hide-md` or `.display-md`. This would be more in line with our `.hide` utility classes.

**Comment by wshirey** [comment]
That sounds better. It's more declarative and self-documenting.

**Comment by scurker** [comment]
@wshirey If you wouldn't mind taking a look at #69, it should address having responsive display utility classes. You would simply use `.display-*-block` or `.display-*-inline-block` where appropriate.
