### ISSUE TITLE
Adjust contrast for button groups when one is depressed

### ISSUE THREAD

**Issue by willsansbury** [daxko/design#9]
Make it clear which one is "pressed." 
Consider darker grey bg so contrast is strong.

**Comment by scurker** [comment]
Playing around with the visual contrast on active buttons:

**Original Buttons**
![original-btn](https://cloud.githubusercontent.com/assets/1062039/7995248/e7d7ae8a-0ad9-11e5-816d-b88293f74de6.png)

**Darker Buttons**
![darker-btn](https://cloud.githubusercontent.com/assets/1062039/7995249/e7dee894-0ad9-11e5-987d-1d20a382f7da.png)

The darker color is set on the active state with `background-color: darken($btn-color, 10%);`

We will need to keep in mind that we'll also have to adjust the active state for `.btn-primary` and `.btn-danger` if we add an additional background color to active buttons.
